This is makeindex, version 2.15 [TeX Live 2020/W32TeX] (kpathsea + Thai support).
Scanning style file ./Dokumentation_BT-Projekt.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Dokumentation_BT-Projekt.acn....done (83 entries accepted, 0 rejected).
Sorting entries....done (613 comparisons).
Generating output file Dokumentation_BT-Projekt.acr....done (42 lines written, 0 warnings).
Output written in Dokumentation_BT-Projekt.acr.
Transcript written in Dokumentation_BT-Projekt.alg.
